kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: busybox:latest
      command:
        - "/bin/sh"
      args:
        - "-c"
        #- "touch /mnt/SUCCESS && exit 0 || exit 1"
        - "while true; do echo $(date -u) >> /mnt/out.txt; sleep 5; done"
      volumeMounts:
        - name: efs-pvc
          mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs
