---
apiVersion: v1
kind: Service
metadata:
  name: "source-ip-app-internal-nlb"
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: source-ip-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080