---
apiVersion: v1
kind: Service
metadata:
  name: source-ip-app-headless-service
spec:
  clusterIP: None # <--
  selector:
    app: source-ip-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
