apiVersion: v1
kind: Pod
metadata:
  name: bosybox
spec:
  containers:
    - name: bosybox
      image: busybox:latest
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done",
        ]
