apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcr-eksworkshop-private
  region: cn-northwest-1

vpc:
  subnets:
    private:
      cn-northwest-1a: { id: subnet-0a9b71430bed40289 }
      cn-northwest-1b: { id: subnet-0bb78e65f98693f5c }
      cn-northwest-1c: { id: subnet-061d15db051dbd091 }
    public:
      cn-northwest-1a: { id: subnet-0d57362f982b609e8 }
      cn-northwest-1b: { id: subnet-0b5e9dbeafa92f0c7 }
      cn-northwest-1c: { id: subnet-01acec79e607f2e6e }
nodeGroups:
  - name: private-ng-1-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true