apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcr-zhy-eksworkshop-private
  region: cn-northwest-1

vpc:
  subnets:
    private:
      cn-northwest-1a: { id: subnet-08e92d36361769d94 }
      cn-northwest-1b: { id: subnet-0c9d2d88b867ba732 }
      cn-northwest-1c: { id: subnet-0fcc93b65339f44b6 }
    public:
      cn-northwest-1a: { id: subnet-074ea0dcbe0513967 }
      cn-northwest-1b: { id: subnet-08bbdc2052361af5e }
      cn-northwest-1c: { id: subnet-01223122c480a5c17 }
nodeGroups:
  - name: private-ng-1-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true