---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: fsx-sc
provisioner: fsx.csi.aws.com
parameters:
    subnetId: subnet-076b60005783f3909
    securityGroupIds: sg-0393037797d388bd4
    s3ImportPath: s3://eks-fsx-lustre-tbztxlpgrzetnzafcxsneuypmfltpexo
    s3ExportPath: s3://eks-fsx-lustre-tbztxlpgrzetnzafcxsneuypmfltpexo/export
    deploymentType: SCRATCH_2
mountOptions:
    - flock
