apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-nlb
  name: nginx-nlb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-nlb
  template:
    metadata:
      labels:
        app: nginx-nlb
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: "service-nginx-nlb"
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: nginx-nlb
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80